### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nevrome** [sidora-tools/sidora.core#10]
We need a software license for this and the other sidora repos

**Comment by stschiff** [comment]
I think you can just add `MIT` to the `DESCRIPTION` file, can't you? That's what I did for sidora.cli.

**Comment by nevrome** [comment]
Ja - MIT would be OK with me. `usethis::use_mit_license()`.

Or should we go with GPL? At the moment this code is not very important, but in the future there might be a public version of Pandora.

**Comment by jfy133** [comment]
Yup MIT is also fine with me.

I don't think we care so much if companies use the code as this is technically internal for us anyway. I will also add to the web app

**Comment by jfy133** [comment]
@nevrome is there any difference between using the github LICENSE file vs what is needed ofr a typical R package/CRAN?

**Comment by nevrome** [comment]
I don't think so, @jfy133. But you have to mention the license file in the DESCRIPTION

```
License: MIT + file LICENSE
```
