### ISSUE TITLE
Standardized variable names

### ISSUE THREAD

**Issue by nevrome** [sidora-tools/sidora.core#13]
A shower thought led me to an idea for a very simple filter function implementation in sidora.cli, which is almost as powerful as the one in the webinterface. Hacking together the prototype made me realize that the current join function causes variables to have different names depending on which tables are merged. That was clear from the beginning, but now I realized that this is highly confusing. 

I therefore suggest to rename all variables at download to include the table name: e.g. `Id` in table `TAB_Site` should become `Id.site`, `Protocol` in table `TAB_Sample` should become `Protocol.sample` and so forth.

This change will break current code (!), but it will tremendously simplify things down the line, because variable names become reliable. Especially useful for high-overlap variables like `tag`.

Discussion about this is scheduled for next friday: @jfy133 @stschiff @nevrome

**Comment by jfy133** [comment]
I'm for this!

I personally would argue to flip it though to `site.Id`, for example, because context is important, as you implied.

**Comment by jfy133** [comment]
@nevrome close this if finished!
