### ISSUE TITLE
Data and lookup table/function organisation

### ISSUE THREAD

**Issue by jfy133** [sidora-tools/sidora.core#19]
As i nthe title.

**Comment by nevrome** [comment]
I think we could go with two data tables (in `data_raw` and then in the namespace of the package): 

1. `pandora_colum_types.tsv` -> `pandora_colum_types` with table names, entity_names, column names and column types
2. `pandora_tables.tsv` -> `pandora_tables` with table names, entity names, aux (?), name/full_id

The lookups in the package are done with internal hash tables. All useful lookup functions are exported (eg. entity2table, table2entity, ...). Ideally the user never has to implement a lookup manually with `1.` and `2.` above, but can use a convenient (and fast!) lookup function.

**Comment by jfy133** [comment]
This was recently implemented with a big re-write by @nevrome. Note the following issues:

- [ ] sample: 'sample.Type' gets translated wierdly, with some tooth/clculus FDI values (i.e. numbers) are translated into strings of bones (e.g. Calculus group and Type as Tibia).
- [ ] sample: `sample.Protocol` some are translated but Id `14` is not.
- [ ] sample: `sample.Batch` is not translated at all and all have the same value (17785) [but I think this was recently added, so maybe this is a 'null' Id?] 
- [ ] All location columns are shifted or just Ids

**Comment by nevrome** [comment]
Excellent debugging! Thank you!
