### ISSUE TITLE
coding join_df_list

### ISSUE THREAD

**Issue by stschiff** [sidora-tools/sidora.core#2]
@nevrome, thanks for getting this started! I'm learning a lot from going through your code. As a test whether I'm getting things right, I'd like to run by you a suggestion for improving `join_df_list`, which I find currently 
1) doesn't expose its true input requirements (two tables).
2) modifies the input list in place (scary)
3) requires an additional function `check_completeness`, which I think we don't need.

How about this:
```
join_df_list <- function(parent, child) {
  ret <- NULL
  if(names(parent) == "TAB_Site" & names(child) == "TAB_Individual") {
    ret <- dplyr::left_join(
      child, 
      parent, 
      by = ("Site" = "Id"), 
      suffix = c(".Individual", ".Site")
    )
  }
  if(names(parent) == "TAB_Individual" & names(child) == "TAB_Sample") {
    ret <- dplyr::left_join(
      child, 
      parent, 
      by = ("Individual" = "Id"), 
      suffix = c(".Sample", ".Individual")
    )
  }
  if(names(parent) == "TAB_Sample" & names(child) == "TAB_Extract") {
    ret <- dplyr::left_join(
      child, 
      parent, 
      by = ("Sample" = "Id"), 
      suffix = c(".Extract", ".Sample")
    )
  }
  if(names(parent) == "TAB_Extract" & names(child) == "TAB_Library") {
    ret <- dplyr::left_join(
      child, 
      parent, 
      by = ("Extract" = "Id"), 
      suffix = c(".Library", ".Extract")
    )
  }
  if(is.null(ret))
    stop("Error: Inputs need to be named by Pandora table names and/or missing intermediate table.")
  else
    return(ret)
}
```

You would call this for example as `join_df_list(c("TAB_Site"=site_tab), c("TAB_Individual"=ind_tab))`.

I'm happy to make a PR, but as I'm still learning R I'd like to make sure I'm not missing something trivial...

**Comment by nevrome** [comment]
Hm - you're right - modifying the input list is a little bit hacky, but I think it's not so bad here, given the sequential merging procedure.

My implementation allows to merge multiple tables at once, not just two. And I would argue that this is a key feature.

**Comment by stschiff** [comment]
Ah... OK, I expected I must have missed something... so it merges all pairs that are in direct sequence?

**Comment by nevrome** [comment]
Yes. And that's why we need `check_completeness()`. The merging cascade breaks if an intermediate pair is missing. 

This is also just a prototype at the moment. Doesn't include other tables beyond `"TAB_Site", "TAB_Individual", "TAB_Sample", "TAB_Extract", "TAB_Library"`.

**Comment by stschiff** [comment]
OK, cool. Good that I didn't go straight for a PR then.

**Comment by nevrome** [comment]
Check out this example code: 

```
creds <- readLines("playground/.credentials")
con <- DBI::dbConnect(
  RMySQL::MySQL(), 
  host = creds[1],
  user = creds[2],
  password = creds[3],
  db = "pandora"
)

df_list_1 <- get_df_list(c(
  "TAB_Site", "TAB_Individual", "TAB_Sample", "TAB_Extract", "TAB_Library"
), con = con)

join_df_list(df_list_1)

df_list_2 <- get_df_list(c(
  "TAB_Site", "TAB_Individual"
), con = con)

join_df_list(df_list_2)

df_list_3 <- get_df_list(c(
  "TAB_Site", "TAB_Extract"
), con = con)

join_df_list(df_list_3)
```

**Comment by stschiff** [comment]
OK. Wow. This is actually very clever. So I tried `join_df_list(df_list_1)` and it gives back a tibble with 117 columns, merging through the entire cascade. Very cool!

**Comment by stschiff** [comment]
I also misunderstood R's in-place modify. I now remember having read in [advanced R](https://adv-r.hadley.nz) that in-place modify of lists creates duplicates, so this may be hacky but actually save, I think.

**Comment by nevrome** [comment]
Is this issue still relevant or can we close it @stschiff?
