### ISSUE TITLE
enforce_types needs to be more sophisticated

### ISSUE THREAD

**Issue by jfy133** [sidora-tools/sidora.core#20]
Unfortunately it seems we have multiple columns where they have the same name, but different column types.

For example: `individual.Archaeological_ID` is of character, but `sample.Archaeological_ID` is of integer, with integer corresponding to the `indiviudal.Individual.Id` numeric ID.

Also, `sample_type_group.Type_Group`  is character, while `sample_type.Type_Group` is numeric. 

This causes problems in the `sidora.cli view` module when trying to make all columns 'human readable' as they are in the Pandora web page itself.

Solution from @nevrome is to instead of vectors have tables of: `table | column | type `, and modify columns based on this information.

**Comment by nevrome** [comment]
1786883d77144faf1e4a2e962f1a8958df5f700c introduces a completely different design for `enforce_types`. I originally wrote this code for sdsanalysis, but it should work here just as fine. 

There are some special cases like the columns which encode boolean values with "yes"/"no" (e.g. Robot). These should be covered with a dedicated transformation function (or changed in Pandora). Please test this new design.
