### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by nevrome** [sidora-tools/sidora.core#25]
Geographic names often contain non-ascii characters and sidora seems to download them from Pandora in the wrong way. That causes problems at many points downstream -- I have no idea how we managed to miss that until now. 

Related: https://stackoverflow.com/questions/30932708/how-to-change-dplyrtbl-connection-encoding-to-utf8

**Comment by nevrome** [comment]
I learned now that this is a problem specific to the singularity container. Very, very annoying. Could be related to this: https://github.com/rstudio/shiny-server/issues/304

**Comment by nevrome** [comment]
I learned from James that it is NOT specific to the container, but it is the only way I can reproduce it right now. 

"Bad Dürrenberg" -> "Bad D\xfcrrenberg"

**Comment by jfy133** [comment]
Ok, I suspect the issue I have had before is more likely to be shiny specify - from sidoraCMON

```
(process:30510): Pango-WARNING **: 13:50:58.940: Invalid UTF-8 string passed to pango_layout_set_text()
```

Displaying the plot in a normal Rstudio viewer it looks fine:

![image](https://user-images.githubusercontent.com/17950287/88388459-e059a480-cdb4-11ea-9650-c4fb357aec91.png)
![image](https://user-images.githubusercontent.com/17950287/88388486-e94a7600-cdb4-11ea-9289-1778056ee67b.png)

**Comment by nevrome** [comment]
Took me all afternoon and I tried all sorts of nasty things, but I think I finally found a solution. Something with either R >=4.0.0 or rocker/tidyverse is fishy. I replaced it with r-base:3.6.3 (https://github.com/sidora-tools/sidora.cli/commit/d4a082e871e264f983500e7d3bd4615109e0362e) and now `sidora tutorial` works on the cluster. I can finally turn back to actually useful questions :smile:
