### ISSUE TITLE
convert datetime-columns automatically

### ISSUE THREAD

**Issue by stschiff** [sidora-tools/sidora.core#26]
Just playing with this, I release that date-columns are parsed as character vectors in the nibbles. Would be nice to convert them automatically to proper date objects (can't remember what the canonic library for that would be).

**Comment by jfy133** [comment]
Yes, this is something we need to work on the in the future. I had originally set it as date time, but when you try to keep both date and time in R, you're forced to display the time zone, which isn't how Pandora displays it - and I couldn't work out at the time how to remove the time zone info. If you convert it to date only you lose the time information.

My initial idea was therefore to convert date columns to date time when you need it in other contexts, but that didn't seem very efficient.

**Comment by jfy133** [comment]
Library would be lubridate probably

**Comment by stschiff** [comment]
Jup, this code works:

```R
sidora.core::make_complete_table_list(c("TAB_Site", "TAB_Sequencing")) %>%
  sidora.core::get_df_list(con=con) %>%
  sidora.core::join_pandora_tables() %>%
  dplyr::transmute(d=lubridate::ymd_hms(individual.Creation_Date)) %>%
    ggplot(aes(x=d)) + geom_histogram() + scale_x_datetime()
```

**Comment by stschiff** [comment]
So, I guess this would mean either
i) (preferably) some kind of automatic detection of date-formatted string columns to be formatted automatically via `lubridate::ymd_hms())` or
ii) fix the known datetime-columns upfront and just do a conversion step with `get_df_list()` and the like.

**Comment by nevrome** [comment]
We just have to specify date columns in our `enforce_types` pipeline. I suggest to go with the base R `as.POSIXct` to avoid another dependency. If dates are encoded differently in different columns and tables, then we will have to specify date formats as well in an own hash.

**Comment by nevrome** [comment]
```
sidora.core::make_complete_table_list(c("TAB_Site", "TAB_Sequencing")) %>%
    sidora.core::get_df_list(con=con) %>%
    sidora.core::join_pandora_tables() %>%
    dplyr::transmute(d=as.POSIXct(individual.Creation_Date)) %>%
    ggplot(aes(x=d)) + geom_histogram() + scale_x_datetime()
```

**Comment by jfy133** [comment]
Converted to dttm here: https://github.com/sidora-tools/sidora.core/commit/6b160579f0f8dca609c89f9f86a96f216769de6a

**Comment by jfy133** [comment]
@stschiff merged my pr which should contain your request. Please check it is as you expect

**Comment by stschiff** [comment]
Beautiful. Works!
