### ISSUE TITLE
Automatic lookup of capture probe set and other easy-to-lookup columns

### ISSUE THREAD

**Issue by stschiff** [sidora-tools/sidora.core#27]
I think it's a nuisance that things like `capture.Probe_Set` aren't automatically converted to "SG", "TF" and so on. 

Since I know we already have efficient hash-based code to do fast lookups, and that seems to be already implemented automatically on the CLI (in some modules?), I think we should just always do this. What do you think?

Same holds for Workers, sequencing machines, protocols, and other simple string lookups.

**Comment by jfy133** [comment]
Please see the `namecol_value_id()` function.

```
## Libs
library(magrittr)
library(dplyr)
library(sidora.core)
library(readr)

host <- "pandora.server.shh.mpg.de"
password <- "gwnAXrS#63RB"
user <- "pandora_read"

con <- sidora.core::get_pandora_connection()
cache_dir <- '/tmp/sddsssd'

## Perform search
extract_list <- c("MGD001.B", "MGD001.C", "MGD002.B", "MGD006.C", "MGD007.B", "MGD008.B", "MGD009.B", "MGD010.B", "MGD011.B", "MGD015.B", "MGD017.C", "MGD016.C", "MGD018.B", "MGD019.B", "TIR001.B", "TIR002.B", "TIR003.A", "TIR004.A", "TIR005.A", "TIR006.A", "TIR007.C", "TIR015.B", "TIR016.B", "TIR017.B", "TIR018.B", "ERA005.B", "ERA017.C", "ERA023.A", "ALA001.E", "ALA004.C", "ALA011.C", "ALA014.C", "ALA016.C", "ALA028.D", "ALA034.C", "ALA059.B", "ALA061.B", "ALA063.B", "ALA069.B", "ALA070.C", "ALA080.C", "ALA085.B", "ALA086.C", "ALA094.B", "ALA118.F", "ALA119.C", "ALA125.D", "ALA126.D", "ALA127.C", "ALA128.E", "ALA139.D", "XAN008.B", "XAN011.A", "XAN012.A", "ABU003.B", "KEL038.C", "KEL039.B", "ASH137.A", "ASH138.A", "ASH139.A", "ASH140.A", "ASH141.A", "ASH142.A", "ASH143.A", "ASH144.A", "ASH145.A", "ASH146.A")

capture_result <- get_df(con = con, "TAB_Capture") %>%
  filter(grepl(paste(extract_list, collapse = "|"), capture.Full_Capture_Id))

## Get names from IDs
capture_cols2update <- names(capture_result[sidora.core::sidora_col_name_has_aux(names(capture_result))])
capture_result <- capture_result %>% 
  dplyr::mutate(dplyr::across(all_of(capture_cols2update), ~namecol_value_from_id(con = con, sidora_col_name = dplyr::cur_column(), query_id = .x, cache_dir = cache_dir)
  )) 

```

This has not yet been added to CLI yet , but see https://github.com/sidora-tools/sidora.cli/issues/21

**Comment by stschiff** [comment]
Yes, this function is good, but talking about usability here, this isn't exactly very convenient. I would make a bold statement here that I think having to refer to capture.Probe_Set in terms of integer number is _never_ useful. To anyone. So thinking about this more, I think I would be voting for immediately returning "curated" datasets, where these lookups happen immediately on the fly. Or at least can be applied with a single function. Perhaps something like a `sidora.core::curate_default_columns()`:

```
con <- sidora.core::get_pandora_connection()

joint_data <- sidora.core::get_df_list(c("TAB_Individual", "TAB_Sample", "TAB_Extract"), con=con) %>%
  sidora.core::join_pandora_tables() %>%
  sidora.core::curate_default_columns()

```

which would then automatically take columns defined in some default list to be completely removed (like integer IDs and things that are of no interest for downstream-analysis (like the "deleted" column)), and others to be automatically converted using lookups (like worker, probe set, ...)

**Comment by stschiff** [comment]
Here is a list of columns to immediately "translate" during curation:
* `individual.Individual_Id` -> I think this is completely useless for us. Remove.
* `individual.Owning_Institution` -> Lookup
* `individual.Worker` -> Lookup
* `individual.Organism` -> Lookup
* `individual.Deleted` -> Use to remove, and then remove that column
* `individual.Deleted_Date` -> Remove the column
* `individual.File` -> Remove column

* `sample.Sample_Id` -> Useless
* `sample.Type_Group` -> Lookup
* `sample.Type` -> Lookup
* `sample.Protocol` -> Lookup
* `sample.Worker` -> Lookup
* `sample.Batch` (this is a bit unclear to me)
* `sample.Location_Bone_Room` -> Lookup
* `sample.Location_Bone` -> Lookup
* `sample.Location_Powder_Room` -> Lookup
* `sample.Location_Powder` -> Lookup
* `sample.Files` -> Remove column
* `sample.Deleted` -> Use to remove, and then remove that column
* `sample.Deleted_Date` -> Remove the column

* `extract.Extract_Id` -> Useless
* `extract.Protocol` -> Lookup
* `extract.Worker` -> Lookup
* `extract.Batch` -> ?
* `extract.Location_Room` -> Lookup
* `extract.Location` -> Lookup
* `extract.Files` -> Remove column
* `extract.Deleted` -> Use to remove, and then remove that column
* `extract.Deleted_Date` -> Remove the column

...

**Comment by stschiff** [comment]
Sorry, too many to finish. But you get the idea... I'm not fluent enough with dplyr and the symbol-based programming in it, but I think one has to kind of loop through all columns, based on their names and then apply all these predefined lookups and removals. Is that practical to do efficiently?

**Comment by jfy133** [comment]
Maybe I'm misunderstanding but that's exactly what the function I describe above is doing.

Like you said, I agree the numeric IDs are just not useful. I origimally suggested automatically running this on everything in sidora.cli tabulate, but Clemens rightly pointed out that this is computationally heavy which is why he wanted the humanreadable flag 


For dropping columns, that already exists with the `format_as_pandora_existing()` function. So parts of that could definitely be generalised.

**Comment by jfy133** [comment]
The idea behind a `format_as` series of functions would be that you keep at much into at a raw level to allow more 'developer' like people to do other weird and wonderful stuff with those numeric IDs, but anything downstream like exporting our sidora.cli can do the clean formatting then

**Comment by stschiff** [comment]
OK, the code you posted above doesn't work for me (Error `Error in grepl(paste(extract_list, collapse = "|"), capture.Full_Capture_Id) :  object 'capture.Full_Capture_Id' not found`)

But more importantly I'm then not getting what `sidora.core::sidora_col_name_has_aux` or `~namecol_value_from_id` are doing.

Could you provide a more minimal example?

**Comment by jfy133** [comment]
Huh weird. I literally ran it fresh before i sent it to you. I'll check this evening, and give explanation of the other two things, is Clemens can't - picking up Maia now.

**Comment by nevrome** [comment]
James code works for me - @stschiff please check if you have the latest version of sidora.core installed.

The [code of the sidora.core function `namecol_value_from_id`](https://github.com/sidora-tools/sidora.core/blob/c32845e47db289d554461280c852128db0a3b2f3/R/dataprep_lookup_in_pandora.R#L20) should give you a good idea how this lookup is currently implemented. 

I very much support a function that does the translation for everything it knows in a table automatically. I don't care too much how we call it. https://github.com/sidora-tools/sidora.cli/issues/21 is indeed relevant.

**Comment by stschiff** [comment]
I did the install the latest with `remotes::install_github("sidora-tools/sidora.core")` and it says the SHA1 hasn't changed, so I assume I have the latest version. Not sure why it doesn't work.

**Comment by jfy133** [comment]
Maybe try rebuilding?

**Comment by stschiff** [comment]
But I mean, I do understand roughly what the functions do, but I could not find in your code so far any default lists of columns to be substituted. Perhaps you can help me today going through that. I get the feeling that `hash_sidora_col_name_auxiliary_table` or something like that could have this, but I don't get the code.

**Comment by stschiff** [comment]
OK, code runs when I install right from within the repo in rstudio.

**Comment by jfy133** [comment]
The hashes are based on this: https://github.com/sidora-tools/sidora.core/blob/master/data-raw/pandora_column_types.tsv

The `auxiliary_*` columns are the ones say which table to look up and then which 'human readable string' column to use. 

As an example(!) for dropping/keeping columns For the specific context as `format_as_update_existing()` (i.e. when you want to format a table exactly as you would see it when downloading a 'batch upload' templtae on the pandora web page), we use the column `update_col_type`

The hashes are then generated from here: https://github.com/sidora-tools/sidora.core/blob/master/data-raw/data_prep.R, generating different hashes for different contexts.

**Comment by stschiff** [comment]
OK, impressive. This is indeed more or less what I meant. I think it can just be made a bit more convenient to use.

Like this (?):
```R
convert_default_lookup() <- function(df) {
  cols2update <- names(df[sidora.core::sidora_col_name_has_aux(names(df))])
  return (df %>% 
    dplyr::mutate(
      dplyr::across(all_of(cols2update),
                    ~namecol_value_from_id(con = con, sidora_col_name = dplyr::cur_column(), query_id = .x)
      )
    )
  )
}
```
I'll try and perhaps submit a PR. Where should this function go?

**Comment by jfy133** [comment]
Yup good plan. Sorry I didn't make that clear - my code from above was from actual 'working code' for a project so hadn't thought about cleaning it up and actually making a function so far. Maybe that's why I got confused with the problem.

Maybe along with `namecol_value_from_id` here? https://github.com/sidora-tools/sidora.core/blob/master/R/dataprep_lookup_in_pandora.R
