### ISSUE TITLE
Add support for new coredb ID entries 

### ISSUE THREAD

**Issue by jfy133** [sidora-tools/sidora.core#47]
Recently apparently a new field was added to many of the tabs with the Eva labs coreDB ID 

We should include this when people are pulling tables

**Comment by nevrome** [comment]
Alright - so the name of the column seems to be `CoreDB_Id` and it occurs in `TAB_Sample`, `TAB_Extract`, `TAB_Library` and `TAB_Capture`. Do you know why not in `TAB_Sequencing`? 

Right now it's just read as a string column, which is already fine. But we probably still want to add it to our column reference table.

`NA` values are just empty strings - and this column has naturally a lot of them. This brings us again to to the question if we should improve our data-types and value parsing system (#16, #42) some day.

**Comment by jfy133** [comment]
Nope no clue ..

Good point about empty values. Maybe we should just ask Robert to give us a list of every (relevant) column and what the missing value indicator is?
