### ISSUE TITLE
Soften unnecessarily strict check for table download

### ISSUE THREAD

**Issue by nevrome** [sidora-tools/sidora.core#64]
@TCLamnidis and I realized today that we implemented a very strict check for the set of tables that can be downloaded with `get_df`:

https://github.com/sidora-tools/sidora.core/blob/b84ad9df188878b3357c415b9a6bce9f4b3441b2/R/dataprep_get_data.R#L81-L84

I think this could be replaced by a warning, to allow downloading tables not (yet) in `pandora_tables_all`.

**Comment by jfy133** [comment]
I think that's reasonable
