### ISSUE TITLE
Provided environment not working

### ISSUE THREAD

**Issue by TCLamnidis** [sidora-tools/sidora.core#65]
I create a conda environment with the provided `environment.yml` and then install `sidora.core` with the provided commands.

Trying to create a connection object then throws the error:
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'drv' in selecting a method for function 'dbConnect': namespace ‘rlang’ 0.4.11 is already loaded, but >= 1.0.5 is required
```

Using `install.packages('rlang')` to get the latest version of rlang, restarting the session and retrying the command fixed the issue.

**Comment by nevrome** [comment]
Maybe you could have a look, @jfy133. You created the conda environment. I guess it's just a matter of updating the hardcoded dependency here?

https://github.com/sidora-tools/sidora.core/blob/9dc6ffb3581a66c1735fe68ca75953890f7eaeea/environment.yml#L14
