### ISSUE TITLE
date objects

### ISSUE THREAD

**Issue by nevrome** [sidora-tools/sidora.core#8]
@jfy133 

I just wanted to call `sidora.core::get_df` in the main sidora app and found an interesting problem here. First of all this integration should be as simple as replacing this line

https://github.com/jfy133/sidora/blob/e1a724ed8d0493bcc16b1b471e805534ac047f93/app/helpers_loading_data.R#L12

with

`this_table <- sidora.core::get_df(tab, this_con, cache_dir = "data_cache")`

This gives me `Error in as.Date.numeric: 'origin' must be supplied` for some tables when I run the app. I don't really understand where this is coming from, but a fix could be to replace

https://github.com/sidora-tools/sidora.core/blob/b860fabb98d2f1d5e26229c02f56f6481b9a840d/R/enforce_types.R#L39

and 

https://github.com/sidora-tools/sidora.core/blob/b860fabb98d2f1d5e26229c02f56f6481b9a840d/R/enforce_types.R#L49

with 

`dplyr::mutate_if(colnames(.) %in% coltypes_date, as.Date, origin = "1970-01-01") %>%`

Unfortunately this throws `Error in : cannot join a Date object with an object that is not a Date object` for some tables. Do you have an idea where this is coming from?

**Comment by jfy133** [comment]
See my fix!
